<<<<<<< HEAD
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8 # Use the Python version your app requires
    commands:
      # Install dependencies (CodeBuild does this, EB will also do it)
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      # Any tests or compilation steps go here
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*' # Package all files in the repository for deployment
=======
version: 0.2
phases:
  install:
    runtime-versions:
      # CRITICAL: This line must be set to 3.11
      python: 3.11 
    commands:
      # Optional, but good practice
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Starting packaging the application with Python 3.11..."
artifacts:
  files:
    - '**/*'
>>>>>>> c1c98bec3bca497b557543134ccacd7e35077d58
